"""revision de la structure de la base de données

Revision ID: 17924ce4151f
Revises: ed2aa9271780
Create Date: 2026-03-26 11:44:42.995919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17924ce4151f'
down_revision: Union[str, Sequence[str], None] = 'ed2aa9271780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Permissions_id'), 'Permissions', ['id'], unique=False)
    op.create_index(op.f('ix_Permissions_name'), 'Permissions', ['name'], unique=True)
    op.create_table('Roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Roles_id'), 'Roles', ['id'], unique=False)
    op.create_index(op.f('ix_Roles_name'), 'Roles', ['name'], unique=True)
    op.create_table('roles_permissions',
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], )
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['Customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['Products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('Products_owner_id_fkey'), 'Products', type_='foreignkey')
    op.drop_column('Products', 'owner_id')
    op.add_column('Users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Users', 'Roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='foreignkey')
    op.drop_column('Users', 'role_id')
    op.add_column('Products', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('Products_owner_id_fkey'), 'Products', 'Customers', ['owner_id'], ['id'])
    op.drop_table('order_items')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('roles_permissions')
    op.drop_index(op.f('ix_Roles_name'), table_name='Roles')
    op.drop_index(op.f('ix_Roles_id'), table_name='Roles')
    op.drop_table('Roles')
    op.drop_index(op.f('ix_Permissions_name'), table_name='Permissions')
    op.drop_index(op.f('ix_Permissions_id'), table_name='Permissions')
    op.drop_table('Permissions')
    # ### end Alembic commands ###
