"""init

Revision ID: 4cb2d01373bd
Revises: 
Create Date: 2026-02-17 10:57:55.057814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cb2d01373bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('personal_access_tokens_expires_at_index'), table_name='personal_access_tokens')
    op.drop_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), table_name='personal_access_tokens')
    op.drop_table('personal_access_tokens')
    op.drop_table('job_batches')
    op.drop_table('migrations')
    op.drop_table('users')
    op.drop_index(op.f('cache_locks_expiration_index'), table_name='cache_locks')
    op.drop_table('cache_locks')
    op.drop_index(op.f('jobs_queue_index'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('cache_expiration_index'), table_name='cache')
    op.drop_table('cache')
    op.drop_table('failed_jobs')
    op.drop_index(op.f('sessions_last_activity_index'), table_name='sessions')
    op.drop_index(op.f('sessions_user_id_index'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('last_activity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey'))
    )
    op.create_index(op.f('sessions_user_id_index'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('sessions_last_activity_index'), 'sessions', ['last_activity'], unique=False)
    op.create_table('failed_jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('connection', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('queue', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exception', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('failed_at', postgresql.TIMESTAMP(precision=0), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('failed_jobs_pkey')),
    sa.UniqueConstraint('uuid', name=op.f('failed_jobs_uuid_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('cache',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('cache_pkey'))
    )
    op.create_index(op.f('cache_expiration_index'), 'cache', ['expiration'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('queue', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('attempts', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reserved_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('available_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('jobs_queue_index'), 'jobs', ['queue'], unique=False)
    op.create_table('cache_locks',
    sa.Column('key', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('expiration', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('cache_locks_pkey'))
    )
    op.create_index(op.f('cache_locks_expiration_index'), 'cache_locks', ['expiration'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email_verified_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('remember_token', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('migrations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('migration', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('batch', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('migrations_pkey'))
    )
    op.create_table('job_batches',
    sa.Column('id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('total_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_jobs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_job_ids', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cancelled_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('finished_at', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('job_batches_pkey'))
    )
    op.create_table('personal_access_tokens',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tokenable_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('tokenable_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('abilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(precision=0), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('personal_access_tokens_pkey')),
    sa.UniqueConstraint('token', name=op.f('personal_access_tokens_token_unique'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('personal_access_tokens_tokenable_type_tokenable_id_index'), 'personal_access_tokens', ['tokenable_type', 'tokenable_id'], unique=False)
    op.create_index(op.f('personal_access_tokens_expires_at_index'), 'personal_access_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###
