"""rename password to hashed password

Revision ID: 73233c2a536c
Revises: bd34a01fff17
Create Date: 2026-02-20 17:22:09.904640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73233c2a536c'
down_revision: Union[str, Sequence[str], None] = 'bd34a01fff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. On ajoute la colonne en acceptant le vide
    op.add_column('Users', sa.Column('hashed_password', sa.String(), nullable=True))

    # 2. On met un mot de passe bidon pour les anciens (ils devront le changer)
    op.execute("UPDATE \"Users\" SET hashed_password = 'change_me_immediately'")

    # 3. Maintenant on peut forcer le NOT NULL
    op.alter_column('Users', 'hashed_password', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Users', 'hashed_password')
    # ### end Alembic commands ###
