"""Suppression des tables de permissions

Revision ID: cbdcf0871eff
Revises: 17924ce4151f
Create Date: 2026-03-27 11:52:33.533165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdcf0871eff'
down_revision: Union[str, Sequence[str], None] = '17924ce4151f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Permissions_id'), table_name='Permissions')
    op.drop_index(op.f('ix_Permissions_name'), table_name='Permissions')
    op.drop_table('roles_permissions')
    op.drop_table('Permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles_permissions',
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['Permissions.id'], name=op.f('roles_permissions_permission_id_fkey')),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.id'], name=op.f('roles_permissions_role_id_fkey'))
    )
    op.create_table('Permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Permissions_pkey'))
    )
    op.create_index(op.f('ix_Permissions_name'), 'Permissions', ['name'], unique=True)
    op.create_index(op.f('ix_Permissions_id'), 'Permissions', ['id'], unique=False)
    # ### end Alembic commands ###
